# Generated by Django 4.0 on 2021-12-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0003_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
    
